// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class AutoFeedDBContext : DbContext
{
    public AutoFeedDBContext()
    {
    }

    public AutoFeedDBContext(DbContextOptions<AutoFeedDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Barn> Barns { get; set; }

    public virtual DbSet<BarnImage> BarnImages { get; set; }

    public virtual DbSet<BarnIoTDevice> BarnIoTDevices { get; set; }

    public virtual DbSet<ChickenBarn> ChickenBarns { get; set; }

    public virtual DbSet<DataIoT> DataIoTs { get; set; }

    public virtual DbSet<ErrorIoT> ErrorIoTs { get; set; }

    public virtual DbSet<FeedingRule> FeedingRules { get; set; }

    public virtual DbSet<FeedingRuleDetail> FeedingRuleDetails { get; set; }

    public virtual DbSet<FlockChicken> FlockChickens { get; set; }

    public virtual DbSet<Food> Foods { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<IoTDevice> IoTDevices { get; set; }

    public virtual DbSet<LargeChicken> LargeChickens { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Request> Requests { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<Task> Tasks { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Barn>(entity =>
        {
            entity.HasKey(e => e.BarnId).HasName("PK__Barn__C683E3D450B79226");

            entity.ToTable("Barn");

            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.Area)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("area");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createDate");
            entity.Property(e => e.FoodAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("foodAmount");
            entity.Property(e => e.Humidity)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("humidity");
            entity.Property(e => e.Temperature)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("temperature");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.WaterAmount).HasColumnName("waterAmount");
        });

        modelBuilder.Entity<BarnImage>(entity =>
        {
            entity.HasKey(e => e.ImageBarnId).HasName("PK__BarnImag__EA36401D863CE8F6");

            entity.ToTable("BarnImage");

            entity.Property(e => e.ImageBarnId).HasColumnName("imageBarnId");
            entity.Property(e => e.BarnId).HasColumnName("barnId");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasColumnName("url");

            entity.HasOne(d => d.Barn).WithMany(p => p.BarnImages)
                .HasForeignKey(d => d.BarnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BarnImage_Barn");
        });

        modelBuilder.Entity<BarnIoTDevice>(entity =>
        {
            entity.HasKey(e => e.BDeviceId).HasName("PK__BarnIoT___9C4A5818C49F9ECC");

            entity.ToTable("BarnIoT_Device");

            entity.Property(e => e.BDeviceId).HasColumnName("bDeviceID");
            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.DeviceId).HasColumnName("deviceID");
            entity.Property(e => e.InstallationDate).HasColumnName("installationDate");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");

            entity.HasOne(d => d.Barn).WithMany(p => p.BarnIoTDevices)
                .HasForeignKey(d => d.BarnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BarnIoT_Barn");

            entity.HasOne(d => d.Device).WithMany(p => p.BarnIoTDevices)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BarnIoT_Device");
        });

        modelBuilder.Entity<ChickenBarn>(entity =>
        {
            entity.HasKey(e => e.CbarnId).HasName("PK__ChickenB__2D4B3D06550517EB");

            entity.ToTable("ChickenBarn");

            entity.HasIndex(e => e.ChickenLid, "UIX_CBarn_Chicken")
                .IsUnique()
                .HasFilter("([chickenLID] IS NOT NULL AND [status]='active')");

            entity.HasIndex(e => e.FlockId, "UIX_CBarn_Flock")
                .IsUnique()
                .HasFilter("([flockID] IS NOT NULL AND [status]='active')");

            entity.Property(e => e.CbarnId).HasColumnName("CBarnID");
            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.ChickenLid).HasColumnName("chickenLID");
            entity.Property(e => e.ExportDate).HasColumnName("exportDate");
            entity.Property(e => e.FlockId).HasColumnName("flockID");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.StartDate).HasColumnName("startDate");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("status");

            entity.HasOne(d => d.Barn).WithMany(p => p.ChickenBarns)
                .HasForeignKey(d => d.BarnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CBarn_Barn");

            entity.HasOne(d => d.ChickenL).WithOne(p => p.ChickenBarn)
                .HasForeignKey<ChickenBarn>(d => d.ChickenLid)
                .HasConstraintName("FK_CBarn_LargeChicken");

            entity.HasOne(d => d.Flock).WithOne(p => p.ChickenBarn)
                .HasForeignKey<ChickenBarn>(d => d.FlockId)
                .HasConstraintName("FK_CBarn_Flock");
        });

        modelBuilder.Entity<DataIoT>(entity =>
        {
            entity.HasKey(e => e.DataId).HasName("PK__Data_IoT__923E3685818A9ACB");

            entity.ToTable("Data_IoT");

            entity.Property(e => e.DataId).HasColumnName("dataID");
            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.DeviceId).HasColumnName("deviceID");
            entity.Property(e => e.RecordDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("recordDate");
            entity.Property(e => e.SequenceNumber).HasColumnName("sequenceNumber");
            entity.Property(e => e.Value)
                .HasColumnType("decimal(18, 4)")
                .HasColumnName("value");

            entity.HasOne(d => d.Barn).WithMany(p => p.DataIoTs)
                .HasForeignKey(d => d.BarnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataIoT_Barn");

            entity.HasOne(d => d.Device).WithMany(p => p.DataIoTs)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DataIoT_Device");
        });

        modelBuilder.Entity<ErrorIoT>(entity =>
        {
            entity.HasKey(e => e.ErrorId).HasName("PK__ErrorIoT__72C6D596A3604E79");

            entity.ToTable("ErrorIoT");

            entity.Property(e => e.ErrorId).HasColumnName("errorID");
            entity.Property(e => e.BarnId).HasColumnName("barnID");
            entity.Property(e => e.DeviceId).HasColumnName("deviceID");
            entity.Property(e => e.ErrorMessage)
                .IsRequired()
                .HasColumnName("errorMessage");
            entity.Property(e => e.RecordDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("recordDate");
            entity.Property(e => e.Severity)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("severity");

            entity.HasOne(d => d.Barn).WithMany(p => p.ErrorIoTs)
                .HasForeignKey(d => d.BarnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ErrorIoT_Barn");

            entity.HasOne(d => d.Device).WithMany(p => p.ErrorIoTs)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ErrorIoT_Device");
        });

        modelBuilder.Entity<FeedingRule>(entity =>
        {
            entity.HasKey(e => e.RuleId).HasName("PK__FeedingR__121C064189951ADA");

            entity.ToTable("FeedingRule");

            entity.Property(e => e.RuleId).HasColumnName("ruleID");
            entity.Property(e => e.ChickenLid).HasColumnName("chickenLID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.EndDate).HasColumnName("endDate");
            entity.Property(e => e.FlockId).HasColumnName("flockID");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.StartDate).HasColumnName("startDate");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("active")
                .HasColumnName("status");
            entity.Property(e => e.Times).HasColumnName("times");

            entity.HasOne(d => d.ChickenL).WithMany(p => p.FeedingRules)
                .HasForeignKey(d => d.ChickenLid)
                .HasConstraintName("FK_Rule_LargeChicken");

            entity.HasOne(d => d.Flock).WithMany(p => p.FeedingRules)
                .HasForeignKey(d => d.FlockId)
                .HasConstraintName("FK_Rule_Flock");
        });

        modelBuilder.Entity<FeedingRuleDetail>(entity =>
        {
            entity.HasKey(e => e.FeedRuleDetailId).HasName("PK__FeedingR__26A980CAC006492A");

            entity.ToTable("FeedingRuleDetail");

            entity.Property(e => e.FeedRuleDetailId).HasColumnName("feedRuleDetailID");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.FeedHour).HasColumnName("feedHour");
            entity.Property(e => e.FeedMinute).HasColumnName("feedMinute");
            entity.Property(e => e.FoodId).HasColumnName("foodID");
            entity.Property(e => e.RuleId).HasColumnName("ruleID");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");

            entity.HasOne(d => d.Food).WithMany(p => p.FeedingRuleDetails)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Detail_Food");

            entity.HasOne(d => d.Rule).WithMany(p => p.FeedingRuleDetails)
                .HasForeignKey(d => d.RuleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Detail_Rule");
        });

        modelBuilder.Entity<FlockChicken>(entity =>
        {
            entity.HasKey(e => e.FlockId).HasName("PK__FlockChi__6D32C9F15CE43F4A");

            entity.ToTable("FlockChicken");

            entity.Property(e => e.FlockId).HasColumnName("flockID");
            entity.Property(e => e.HealthStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("healthStatus");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.TransferDate).HasColumnName("transferDate");
            entity.Property(e => e.Weight)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("weight");
        });

        modelBuilder.Entity<Food>(entity =>
        {
            entity.HasKey(e => e.FoodId).HasName("PK__Food__77EAEA197C187CAF");

            entity.ToTable("Food");

            entity.Property(e => e.FoodId).HasColumnName("foodID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.HasKey(e => e.InventId).HasName("PK__Inventor__3805E39FC73CB296");

            entity.ToTable("Inventory");

            entity.Property(e => e.InventId).HasColumnName("inventID");
            entity.Property(e => e.ExpiredDate).HasColumnName("expiredDate");
            entity.Property(e => e.FoodId).HasColumnName("foodID");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.WeightPerBag)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("weightPerBag");
            entity.Property(e => e.ImportDate).HasColumnName("importDate");

            entity.HasOne(d => d.Food).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Inventory_Food");
        });

        modelBuilder.Entity<IoTDevice>(entity =>
        {
            entity.HasKey(e => e.DeviceId).HasName("PK__IoT_Devi__84BE14B733BFD97E");

            entity.ToTable("IoT_Device");

            entity.Property(e => e.DeviceId).HasColumnName("deviceID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
        });

        modelBuilder.Entity<LargeChicken>(entity =>
        {
            entity.HasKey(e => e.ChickenLid).HasName("PK__LargeChi__6DE57F4B56CD7219");

            entity.ToTable("LargeChicken");

            entity.Property(e => e.ChickenLid).HasColumnName("chickenLID");
            entity.Property(e => e.FlockId).HasColumnName("flockID");
            entity.Property(e => e.HealthStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("healthStatus");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Url).HasColumnName("url");
            entity.Property(e => e.Weight)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("weight");

            entity.HasOne(d => d.Flock).WithMany(p => p.LargeChickens)
                .HasForeignKey(d => d.FlockId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LargeChicken_Flock");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Report__1C9B4ECD130AF909");

            entity.ToTable("Report");

            entity.Property(e => e.ReportId).HasColumnName("reportID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createDate");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.Url).HasColumnName("url");
            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.User).WithMany(p => p.Reports)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Report_User");
        });

        modelBuilder.Entity<Request>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__Request__E3C5DE51C0DD2609");

            entity.ToTable("Request");

            entity.Property(e => e.RequestId).HasColumnName("requestID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.Url).HasColumnName("url");
            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.User).WithMany(p => p.Requests)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Request_User");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__CD98460A64D3BFDB");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("roleID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("description");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.SchedId).HasName("PK__Schedule__F378328EFB6184D7");

            entity.ToTable("Schedule");

            entity.Property(e => e.SchedId).HasColumnName("schedID");
            entity.Property(e => e.CbarnId).HasColumnName("CBarnID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(CONVERT([date],getdate()))")
                .HasColumnName("createdDate");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.EndDate).HasColumnName("endDate");
            entity.Property(e => e.Note)
                .IsRequired()
                .HasColumnName("note");
            entity.Property(e => e.Priority)
                .HasMaxLength(10)
                .HasDefaultValue("medium")
                .HasColumnName("priority");
            entity.Property(e => e.StartDate).HasColumnName("startDate");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("pending")
                .HasColumnName("status");
            entity.Property(e => e.TaskId).HasColumnName("taskID");
            entity.Property(e => e.UserId).HasColumnName("userID");

            entity.HasOne(d => d.Cbarn).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.CbarnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sched_CBarn");

            entity.HasOne(d => d.Task).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.TaskId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sched_Task");

            entity.HasOne(d => d.User).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sched_User");
        });

        modelBuilder.Entity<Task>(entity =>
        {
            entity.HasKey(e => e.TaskId).HasName("PK__Task__DD5D55A2A36B50C0");

            entity.ToTable("Task");

            entity.Property(e => e.TaskId).HasColumnName("taskID");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.EndTime).HasColumnName("endTime");
            entity.Property(e => e.StartTime).HasColumnName("startTime");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("title");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__CB9A1CDF10FAAC7B");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__AB6E616413269A10").IsUnique();

            entity.HasIndex(e => e.Username, "UQ__User__F3DBC572AAF19E2C").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("userID");
            entity.Property(e => e.AvatarUrl).HasColumnName("avatarURL");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fullName");
            entity.Property(e => e.LastLogin)
                .HasColumnType("datetime")
                .HasColumnName("lastLogin");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.RoleId).HasColumnName("roleID");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("username");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_Role");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}