// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class BarnImage
{
    public int ImageBarnId { get; set; }

    public int BarnId { get; set; }

    public string Url { get; set; }

    public string Description { get; set; }

    public DateTime? CaptureDate { get; set; }

    public virtual Barn Barn { get; set; }
}