// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class ErrorIoT
{
    public int ErrorId { get; set; }

    public int DeviceId { get; set; }

    public int BarnId { get; set; }

    public string ErrorMessage { get; set; }

    public string Severity { get; set; }

    public DateTime? RecordDate { get; set; }

    public virtual Barn Barn { get; set; }

    public virtual IoTDevice Device { get; set; }
}