// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class FeedingSession
{
    public int SessionId { get; set; }

    public int FoodId { get; set; }

    public int? UserId { get; set; }

    public decimal PlannedQuantity { get; set; }

    public decimal? ActualQuantity { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<FeedingSessionDetail> FeedingSessionDetails { get; set; } = new List<FeedingSessionDetail>();

    public virtual Food Food { get; set; }

    public virtual User User { get; set; }
}