// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class FeedingSessionDetail
{
    public int DetailId { get; set; }

    public int SessionId { get; set; }

    public int InventId { get; set; }

    public decimal Quantity { get; set; }

    public virtual Inventory Invent { get; set; }

    public virtual FeedingSession Session { get; set; }
}