// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class FeedingRule
{
    public int RuleId { get; set; }

    public int? ChickenLid { get; set; }

    public int? FlockId { get; set; }

    public int? Times { get; set; }

    public string Description { get; set; }

    public string Note { get; set; }

    public virtual LargeChicken ChickenL { get; set; }

    public virtual ICollection<FeedingRuleDetail> FeedingRuleDetails { get; set; } = new List<FeedingRuleDetail>();

    public virtual FlockChicken Flock { get; set; }
}