// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class FlockChicken
{
    public int FlockId { get; set; }

    public string Name { get; set; }

    public int? Quantity { get; set; }

    public decimal? Weight { get; set; }

    public int? Age { get; set; }

    public string HealthStatus { get; set; }

    public string Note { get; set; }

    public virtual ChickenBarn ChickenBarn { get; set; }

    public virtual FeedingRule FeedingRule { get; set; }

    public virtual ICollection<LargeChicken> LargeChickens { get; set; } = new List<LargeChicken>();
}