// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class FoodStorage
{
    public int StorageId { get; set; }

    public int FoodId { get; set; }

    public int BarnId { get; set; }

    public decimal FoodWeight { get; set; }

    public decimal LeftoverFood { get; set; }

    public string Note { get; set; }

    public virtual Barn Barn { get; set; }

    public virtual Food Food { get; set; }
}