// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class Food
{
    public int FoodId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public string Note { get; set; }

    public virtual ICollection<FeedingRuleDetail> FeedingRuleDetails { get; set; } = new List<FeedingRuleDetail>();

    public virtual ICollection<FoodStorage> FoodStorages { get; set; } = new List<FoodStorage>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();
}