// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class InventoryLog
{
    public int LogId { get; set; }

    public int? FoodId { get; set; }

    public int? InventId { get; set; }

    public string Type { get; set; }

    public decimal? Quantity { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }
}