// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AutoFeed_Backend_DAO.Models;

public partial class Inventory
{
    public int InventId { get; set; }

    public int? FoodId { get; set; }

    public int? Quantity { get; set; }

    public decimal? WeightPerBag { get; set; }

    public DateOnly? ExpiredDate { get; set; }

    public virtual Food Food { get; set; }
}